#!/bin/bash
#
# Copyright (C) 2016 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

cmake_series=3.3
cmake_ver=3.3.0

ecm_series=5.12
ecm_ver=5.12.0

dir=`pwd`

export PATH=$dir/.cmake/$cmake_series/bin:$PATH

# cmake
if [ ! -d $dir/.cmake/$cmake_series/bin ]; then
    rm -rf $dir/.cmake/$cmake_series
    mkdir -p $dir/.cmake
    cmake_basename="cmake-${cmake_ver}-Linux-x86_64"
    wget --no-check-certificate http://www.cmake.org/files/v${cmake_series}/${cmake_basename}.tar.gz -O cmake.tar.gz
    tar -xzf cmake.tar.gz -C $dir
    mv $dir/${cmake_basename} $dir/.cmake/$cmake_series
fi
cmake --version

# extra-cmake-modules
if [ ! -d $dir/.cmake/$cmake_series/share/ECM ]; then
    ecm_basename="extra-cmake-modules-${ecm_ver}"
    wget --no-check-certificate http://download.kde.org/stable/frameworks/${ecm_series}/${ecm_basename}.tar.xz -O ecm.tar.xz
    tar -xJf ecm.tar.xz
    pushd ${ecm_basename}
    rm -rf build
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=$dir/.cmake/$cmake_series
    make && make install
    popd
fi
