#!/bin/bash
#
# Copyright (C) 2016 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

qt_series=5.6
qt_ver=5.6.0

dir=`pwd`

export PATH=$dir/.qt/$qt_series/bin:$PATH

# Qt
if [ ! -d $dir/.qt/$qt_series/$qt_series/gcc_64 ]; then
    rm -rf $dir/.qt/$qt_series
    mkdir -p $dir/.qt
    qt_url="http://download.qt.io/official_releases/qt/${qt_series}/${qt_ver}"
    qt_basename="qt-opensource-linux-x64-${qt_ver}"
    wget --no-check-certificate ${qt_url}/${qt_basename}.run
    wget --no-check-certificate ${qt_url}/${qt_basename}.run.sha256
    sha256sum -c ${qt_basename}.run.sha256 || exit $?
    curl https://raw.githubusercontent.com/hawaii-desktop/repotools/master/ci/extract-qt-installer >extract-qt-installer
    chmod u+x extract-qt-installer
    QT_QPA_PLATFORM=minimal ./extract-qt-installer ${qt_basename}.run $dir/.qt/$qt_series
fi
