#!/bin/bash
#
# Copyright (C) 2016 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

xcb_series=1.11
xcb_ver=1.11.1

dir=`pwd`

export PATH=$dir/.xcb/$xcb_series/bin:$PATH

# xcb
if [ ! -d $dir/.xcb/$xcb_series/bin ]; then
    rm -rf $dir/.xcb/$xcb_series
    mkdir -p $dir/.xcb

    xcb_proto_basename="xcb-proto-$xcb_series"
    wget --no-check-certificate http://xcb.freedesktop.org/dist/xcb-proto-1.11.tar.bz2 -O proto.tar.bz2
    tar -xjf proto.tar.bz2
    pushd ${xcb_proto_basename}
    ./configure --prefix=$dir/.xcb/$xcb_series
    make && make install
    popd

    xcb_basename="libxcb-${xcb_ver}"
    wget --no-check-certificate http://xcb.freedesktop.org/dist/${xcb_basename}.tar.bz2 -O xcb.tar.bz2
    tar -xjf xcb.tar.bz2
    pushd ${xcb_basename}
    ./configure --prefix=$dir/.xcb/$xcb_series --enable-xkb
    make && make install
    popd
fi
