/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DisplayManagerAdapter -a DisplayManagerAdapter.h:DisplayManagerAdapter.cpp org.freedesktop.Displaymanager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DISPLAYMANAGERADAPTER_H_1364069208
#define DISPLAYMANAGERADAPTER_H_1364069208

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.DisplayManager
 */
class DisplayManagerAdapter: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.DisplayManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.DisplayManager\">\n"
"    <method name=\"SwitchToGreeter\"/>\n"
"    <method name=\"SwitchToUser\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"    </method>\n"
"    <method name=\"SwitchToGuest\"/>\n"
"  </interface>\n"
        "")
public:
    DisplayManagerAdapter(QObject *parent);
    virtual ~DisplayManagerAdapter();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void SwitchToGreeter();
    void SwitchToGuest();
    void SwitchToUser(const QString &username);
Q_SIGNALS: // SIGNALS
};

#endif
