/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DisplayManagerAdapter -a DisplayManagerAdapter.h:DisplayManagerAdapter.cpp org.freedesktop.Displaymanager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "DisplayManagerAdapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DisplayManagerAdapter
 */

DisplayManagerAdapter::DisplayManagerAdapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DisplayManagerAdapter::~DisplayManagerAdapter()
{
    // destructor
}

void DisplayManagerAdapter::SwitchToGreeter()
{
    // handle method call org.freedesktop.DisplayManager.SwitchToGreeter
    QMetaObject::invokeMethod(parent(), "SwitchToGreeter");
}

void DisplayManagerAdapter::SwitchToGuest()
{
    // handle method call org.freedesktop.DisplayManager.SwitchToGuest
    QMetaObject::invokeMethod(parent(), "SwitchToGuest");
}

void DisplayManagerAdapter::SwitchToUser(const QString &username)
{
    // handle method call org.freedesktop.DisplayManager.SwitchToUser
    QMetaObject::invokeMethod(parent(), "SwitchToUser", Q_ARG(QString, username));
}

