.TH USAGE: "1" "May 2013" "Usage: sddm-greeter [options]" "User Commands"
.SH NAME
sddm -  a QML-based, highly configurable, login manager
.SH DESCRIPTION
A modern display manager for X11 It uses modern technologies like QtQuick, which in turn gives the designer the ability to create smooth, animated user interfaces..SH SYNOPSIS
.B sddm-greeter
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-theme\fR <theme path>
Test greeter theme
\fB\-\-socket\fR <socket path>
Set socket name
.SH FILES
configuration can be done with the main configuration file at:
.I /etc/sddm.conf 
all themes are by default found at:
.I /usr/share/apps/sddm/themes
.SH "SEE ALSO"
The full documentation for sddm is avaialble at https://github.com/sddm/sddm
.SH AUTHORS
Abdurrahman Avci (abdurrahmanavci@gmail.com)
Christopher Roy Bratusek (nano@tuxfamily.org)


