#!/bin/bash
############################################################################
# Copyright (c) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
############################################################################

export prev=$1
export next=$2

export contributors=`git shortlog v${prev}..develop -sn --no-merges | awk -F'\t' '{print $2}' | tr -s "\\n" "*" | sed -e 's@*@, @g' -e 's@, $@\n@g'`
export logs=`git shortlog v${prev}..develop --no-merges --format="%s - [link](https://github.com/sddm/sddm/commit/%h)" | sed -e 's,^      ,  * ,g'`

cat template.txt | envsubst
